//
//  SearchCharacterInteractor.swift
//  Rick and Morti
//
//  Created by Youchen Zhou on 10/2/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchCharacterBusinessLogic
{
    func saveFilter(searchFilter: SearchCharacterFilter)
}

protocol SearchCharacterDataStore
{
  var searchFilter: SearchCharacterFilter? { get set }
}

class SearchCharacterInteractor: SearchCharacterBusinessLogic, SearchCharacterDataStore
{
    var searchFilter: SearchCharacterFilter?
    
  var presenter: SearchCharacterPresentationLogic?
  var worker: SearchCharacterWorker?
  
    func saveFilter(searchFilter: SearchCharacterFilter){
        self.searchFilter = searchFilter
    }
}
