//
//  CharacterDetailWorker.swift
//  Rick and Morti
//
//  Created by Youchen Zhou on 6/2/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CharacterDetailWorker
{
    
    var characterApi: EpisodesProtocol
    
    init(charancterApi: EpisodesProtocol) {
        self.characterApi = charancterApi
    }
    
    func fetchMultipleEpisodes(episodesIds: [Int], completionHandler: @escaping ([Episode]) -> Void, errorHandler: @escaping (ServiceOperationError) -> Void){
        characterApi.fetchEpisodesById(episodesIds: episodesIds) { serviceResult in
            switch serviceResult{
            case .Success(let result):
                completionHandler(result)
            case .Failure(let error):
                errorHandler(error)
            }
        }
    }
    
    func fetchSingleEpisode(episodeId: Int, completionHandler: @escaping (Episode) -> Void, errorHandler: @escaping (ServiceOperationError) -> Void){
        characterApi.fetchEpisode(episodeId: episodeId) { serviceResult in
            switch serviceResult{
            case .Success(let result):
                completionHandler(result)
            case .Failure(let error):
                errorHandler(error)
            }
        }
    }
}
