//
//  CharacterDetailModels.swift
//  Rick and Morti
//
//  Created by Youchen Zhou on 6/2/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CharacterDetail
{
  // MARK: Use cases
  
  enum GetCharacter
  {
    struct Request
    {
    }
    struct Response
    {
        var character: Character
    }
    struct ViewModel
    {
        var character: Character
    }
  }
    
    enum FetchEpisodes
    {
        struct Request
        {
            var episodesId: [Int] = []
        }
        struct Response
        {
            var episodes: [Episode]
        }
        struct ViewModel{
            struct DisplayedEpisode{
                var name: String
                var air_date: String
                var episode: String
            }
            
            var displayedEpisodes: [DisplayedEpisode]
        }
    }
}
