//
//  SearchCharacterListRouter.swift
//  Rick and Morti
//
//  Created by Youchen Zhou on 13/2/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SearchCharacterListRoutingLogic
{
    func routeToShowCharacterFromSearch(segue: UIStoryboardSegue?)
}

protocol SearchCharacterListDataPassing
{
  var dataStore: SearchCharacterListDataStore? { get }
}

class SearchCharacterListRouter: NSObject, SearchCharacterListRoutingLogic, SearchCharacterListDataPassing
{
  weak var viewController: SearchCharacterListViewController?
  var dataStore: SearchCharacterListDataStore?
  
  // MARK: Routing
  
  func routeToShowCharacterFromSearch(segue: UIStoryboardSegue?)
  {
      if let segue = segue {
          let destinationVC = segue.destination as! CharacterDetailViewController
          var destinationDS = destinationVC.router!.dataStore!
          passDataToCharacterDetail(source: dataStore!, destination: &destinationDS)
      } else {
        let destinationVC = viewController?.storyboard?.instantiateViewController(withIdentifier: "CharacterDetailViewController") as! CharacterDetailViewController
        var destinationDS = destinationVC.router!.dataStore!
          passDataToCharacterDetail(source: dataStore!, destination: &destinationDS)
          navigateToCharacterDetail(source: viewController!, destination: destinationVC)
      }
  }

  // MARK: Navigation
  
  func navigateToCharacterDetail(source: SearchCharacterListViewController, destination: CharacterDetailViewController)
  {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  func passDataToCharacterDetail(source: SearchCharacterListDataStore, destination: inout CharacterDetailDataStore)
  {
      let selectedRow = viewController?.tableView.indexPathForSelectedRow?.row
      destination.character = source.characters?[selectedRow!]
  }
}
