//
//  SearchCharacterListViewController.swift
//  Rick and Morti
//
//  Created by Youchen Zhou on 13/2/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchCharacterListDisplayLogic: NSObject
{
    func displayFetchedCharacters(viewModel: SearchCharacterList.SearchCharacter.ViewModel)
    func displayNewPageCharacters(viewModel: SearchCharacterList.SearchCharacter.ViewModel)
    func displayError(msg: String)
}

class SearchCharacterListViewController: UITableViewController, SearchCharacterListDisplayLogic
{
    
  var interactor: SearchCharacterListBusinessLogic?
  var router: (NSObjectProtocol & SearchCharacterListRoutingLogic & SearchCharacterListDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = SearchCharacterListInteractor()
    let presenter = SearchCharacterListPresenter()
    let router = SearchCharacterListRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
      super.viewDidLoad()
      self.tableView.register(UINib(nibName: "CharacterCell", bundle: nil), forCellReuseIdentifier: "CharacterCell")
      fetchCharactersFiltered()
  }
  
  // MARK: Fetch characters filtered
    
    var hasNextPage = false
    var displayedCharacters = [SearchCharacterList.SearchCharacter.ViewModel.DisplayedCharacter]()
    var displayedImages: [Int: UIImage] = [:]
    
    func fetchCharactersFiltered(){
        let request = SearchCharacterList.SearchCharacter.Request()
        interactor?.fetchCharactersFiltered(request: request)
    }
    
    func displayFetchedCharacters(viewModel: SearchCharacterList.SearchCharacter.ViewModel)
    {
        self.hasNextPage = viewModel.hasNextPage
        displayedCharacters = viewModel.displayedCharacters
        tableView.reloadData()
    }
    
    func displayError(msg: String){
        self.showAlert(title: "Error", message: msg)
    }
    
    override func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return displayedCharacters.count
    }
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let displayedCharacter = displayedCharacters[indexPath.row]
        let image = displayedImages[displayedCharacter.id]
        let cell = tableView.dequeueReusableCell(withIdentifier: "CharacterCell") as? CharacterCell
        cell?.characterImage.image = image
        if image == nil {
            loadImage(for: displayedCharacter, rowAt: indexPath)
        }
        cell?.nameLabel.text = displayedCharacter.name
        cell?.statusLabel.text = displayedCharacter.status
        return cell!
    }
    
    override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let cell = tableView.cellForRow(at: indexPath)
        performSegue(withIdentifier: "ShowCharacterFromSearch", sender: cell)
    }
    
    // MARK: Load image
    func loadImage(for displayedCharacter: SearchCharacterList.SearchCharacter.ViewModel.DisplayedCharacter,rowAt indexPath: IndexPath){
        getRemoteImage(from: displayedCharacter.image) { image in
            DispatchQueue.main.async {
                self.displayedImages[displayedCharacter.id] = image
                self.tableView.reloadRows(at: [indexPath], with: .automatic)
            }
        }
    }
    
    //MARK: Pagination
    var isFetchingNextPage = false
    
    func displayNewPageCharacters(viewModel: SearchCharacterList.SearchCharacter.ViewModel) {
        self.hasNextPage = viewModel.hasNextPage
        self.displayedCharacters.append(contentsOf: viewModel.displayedCharacters)
        self.tableView.reloadData()
        self.isFetchingNextPage = false
        self.tableView.tableFooterView = nil
    }
    
    override func scrollViewDidScroll(_ scrollView: UIScrollView) {
        guard hasNextPage == true else{
            return
        }
        
        let ROW_HEIGHT: Float = 88.0
        let NUMBER_OF_ROW_BEFORE_LOADING: Float = 4
        let ROWS_HEIGHT_BEFORE_LOADING = ROW_HEIGHT * NUMBER_OF_ROW_BEFORE_LOADING
        
        let position = scrollView.contentOffset.y
        if position > (tableView.contentSize.height - CGFloat(ROWS_HEIGHT_BEFORE_LOADING)) - scrollView.frame.size.height  {
            guard !self.isFetchingNextPage else {
                return
            }
            fetchNextPage()
        }
    }
    
    
    func fetchNextPage(){
        self.isFetchingNextPage = true
        DispatchQueue.main.async {
            self.tableView.tableFooterView = self.createFotterSpinnerView()
        }
        
        let request = SearchCharacterList.SearchCharacter.Request()
        interactor?.fetchNextPageCharacters(request: request)
    }
    
}
