//
//  SearchCharacterListModels.swift
//  Rick and Morti
//
//  Created by Youchen Zhou on 13/2/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SearchCharacterList
{
  // MARK: Use cases
  
  enum SearchCharacter
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
        struct DisplayedCharacter {
            var id: Int
            var image: String
            var name: String
            var race: String
            var status: String
        }
        var displayedCharacters: [DisplayedCharacter]
        var hasNextPage: Bool
    }
  }
}
