//
//  ListCharactersRouter.swift
//  Rick and Morti
//
//  Created by Youchen Zhou on 4/2/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListCharactersRoutingLogic
{
    func routeToShowCharacter(segue: UIStoryboardSegue?)
}

protocol ListCharactersDataPassing
{
  var dataStore: ListCharactersDataStore? { get }
}

class ListCharactersRouter: NSObject, ListCharactersRoutingLogic, ListCharactersDataPassing
{
  weak var viewController: ListCharactersViewController?
  var dataStore: ListCharactersDataStore?
  
  // MARK: Routing
    
    func routeToShowCharacter(segue: UIStoryboardSegue?)
    {
      if let segue = segue {
          let destinationVC = segue.destination as! CharacterDetailViewController
          var destinationDS = destinationVC.router!.dataStore!
          passDataToCharacterDetail(source: dataStore!, destination: &destinationDS)
      } else {
        let destinationVC = viewController?.storyboard?.instantiateViewController(withIdentifier: "CharacterDetailViewController") as! CharacterDetailViewController
        var destinationDS = destinationVC.router!.dataStore!
          passDataToCharacterDetail(source: dataStore!, destination: &destinationDS)
          navigateToCharacterDetail(source: viewController!, destination: destinationVC)
      }
    }
  
    // MARK: Navigation
  
    func navigateToCharacterDetail(source: ListCharactersViewController, destination: CharacterDetailViewController)
    {
        source.show(destination, sender: nil)
    }
  
    // MARK: Passing data
  
    func passDataToCharacterDetail(source: ListCharactersDataStore, destination: inout CharacterDetailDataStore)
    {
        let selectedRow = viewController?.tableView.indexPathForSelectedRow?.row
        destination.character = source.characters?[selectedRow!]
    }
}
