//
//  ListEpisodesModels.swift
//  Rick and Morti
//
//  Created by Youchen Zhou on 10/2/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListEpisodes
{
  // MARK: Use cases
  
  enum FetchEpisodes
  {
      struct Request
      {
      }
      struct Response: Codable
      {
          var info: PaginationInfo
          var results: [Episode]
      }
      struct ViewModel
      {
          struct DisplayedEpisode {
              var name: String
              var air_date: String
              var episode: String
          }
          var displayedEpisodes: [DisplayedEpisode]
          var hasNextPage: Bool
      }
  }
}
