//
//  ListEpisodesWorker.swift
//  Rick and Morti
//
//  Created by Youchen Zhou on 10/2/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ListEpisodesWorker
{
    var episodesApi: EpisodesProtocol
    
    init(episodesApi: EpisodesProtocol) {
        self.episodesApi = episodesApi
    }
    
    func fetchEpisodes(completionHandler: @escaping (EpisodesPageApiResponse) -> Void, errorHandler: @escaping (ServiceOperationError) -> Void){
        episodesApi.fetchEpisodesFirstPage { serviceResult in
          switch serviceResult{
          case .Success(let result):
              completionHandler(result)
          case .Failure(let error):
              errorHandler(error)
          }
      }
    }
    
    func fetchNextPage(urlString: String, completionHandler: @escaping (EpisodesPageApiResponse) -> Void, errorHandler: @escaping (ServiceOperationError) -> Void){
        episodesApi.fetchEpisodesNextPage(urlString: urlString) {
            serviceResult in
                switch serviceResult{
                case .Success(let result):
                    completionHandler(result)
                case .Failure(let error):
                    errorHandler(error)
                }
        }
    }
}
